import assert from "node:assert/strict";
import test from "node:test";
import {
  getPreviewRecipientLines,
  getPreviewReference,
  getPreviewStatus,
  isGoodsTransferTemplate,
  OFFICIAL_DOCUMENT_TEMPLATE_PREVIEWS,
} from "./official-document-template-preview.support";

const prefixes = {
  gtnPrefix: "GTN",
  invoicePrefix: "INV",
  receiptPrefix: "RCT",
};

test("lists the document templates currently generated by the system", () => {
  assert.deepEqual(
    OFFICIAL_DOCUMENT_TEMPLATE_PREVIEWS.map((template) => template.key),
    ["sales_receipt", "credit_note", "goods_transfer_note"],
  );
});

test("builds preview references from document settings", () => {
  assert.equal(
    getPreviewReference("sales_receipt", prefixes),
    "RCT-PREVIEW-001",
  );
  assert.equal(getPreviewReference("credit_note", prefixes), "INV-000042-CN");
  assert.equal(
    getPreviewReference("goods_transfer_note", prefixes),
    "GTN-PREVIEW-001",
  );
});

test("uses document-specific status and recipient copy", () => {
  assert.equal(getPreviewStatus("sales_receipt"), "Confirmed");
  assert.equal(getPreviewStatus("credit_note"), "Refund processed");
  assert.equal(getPreviewStatus("goods_transfer_note"), "In transit");
  assert.match(
    getPreviewRecipientLines("goods_transfer_note")[0] ?? "",
    /Source/,
  );
});

test("identifies the GTN template for transfer-specific preview layout", () => {
  assert.equal(isGoodsTransferTemplate("goods_transfer_note"), true);
  assert.equal(isGoodsTransferTemplate("sales_receipt"), false);
  assert.equal(isGoodsTransferTemplate("credit_note"), false);
});
