import {
  BarChart3,
  Boxes,
  ClipboardList,
  MessageSquareText,
  PackageSearch,
  ShoppingCart,
  Store,
  Truck,
} from "lucide-react";
import { toRoute } from "@/lib/routes";
import type { NavRegistryEntry } from "./portal-shell-config.types";

export const COMMERCE_CATALOG_SUPPLY_NAV_REGISTRY: readonly NavRegistryEntry[] =
  [
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/sales" }],
      description:
        "Daily sales ledger and revenue movement across visible shops.",
      href: toRoute("/admin/sales"),
      icon: BarChart3,
      label: "Sales ledger",
      requiredPermission: "pos.sales.manage",
      section: "Commerce",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/orders" }],
      description: "View and manage customer orders across all locations.",
      href: toRoute("/admin/orders"),
      icon: ShoppingCart,
      label: "Orders",
      requiredPermission: "orders.view",
      section: "Commerce",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/deliveries" }],
      description: "Track and manage delivery operations platform-wide.",
      href: toRoute("/admin/deliveries"),
      icon: Truck,
      label: "Deliveries",
      requiredPermission: "deliveries.view",
      section: "Commerce",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/products" }],
      description: "Manage products, variants, and catalogue structure.",
      href: toRoute("/admin/products"),
      icon: PackageSearch,
      label: "Products",
      requiredPermission: "catalog.view",
      section: "Catalog",
    },
    {
      activeMatchers: [{ mode: "exact", path: "/admin/products/new" }],
      description: "Create a new product.",
      href: toRoute("/admin/products/new"),
      icon: PackageSearch,
      label: "New product",
      requiredPermission: "catalog.products.manage",
      section: "Catalog",
      sidebar: false,
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/products/brands" }],
      description: "Create and manage brand entities for the catalogue.",
      href: toRoute("/admin/products/brands"),
      icon: Store,
      label: "Brands",
      requiredPermission: "catalog.brands.manage",
      section: "Catalog",
    },
    {
      activeMatchers: [{ mode: "exact", path: "/admin/products/brands/new" }],
      description: "Create a new brand.",
      href: toRoute("/admin/products/brands/new"),
      icon: Store,
      label: "New brand",
      requiredPermission: "catalog.brands.manage",
      section: "Catalog",
      sidebar: false,
    },
    {
      activeMatchers: [
        { mode: "descendants", path: "/admin/products/categories" },
      ],
      description: "Create and manage product categories.",
      href: toRoute("/admin/products/categories"),
      icon: Boxes,
      label: "Categories",
      requiredPermission: "catalog.categories.manage",
      section: "Catalog",
    },
    {
      activeMatchers: [
        { mode: "exact", path: "/admin/products/categories/new" },
      ],
      description: "Create a new category.",
      href: toRoute("/admin/products/categories/new"),
      icon: Boxes,
      label: "New category",
      requiredPermission: "catalog.categories.manage",
      section: "Catalog",
      sidebar: false,
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/stock/balances" }],
      description: "On-hand, reserved, and available stock per location.",
      href: toRoute("/admin/stock/balances"),
      icon: Boxes,
      label: "Stock levels",
      locationSelectorPermission: null,
      requiredPermission: "admin.dashboard.view",
      section: "Supply",
    },
    {
      activeMatchers: [
        { mode: "descendants", path: "/admin/stock/reservations" },
      ],
      description: "Inspect active stock reservations across the platform.",
      href: toRoute("/admin/stock/reservations"),
      icon: Boxes,
      label: "Reservations",
      locationSelectorPermission: null,
      requiredPermission: "admin.dashboard.view",
      section: "Supply",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/stock/takes" }],
      description: "Generate printable stock-take sheets and count booklets.",
      href: toRoute("/admin/stock/takes"),
      icon: ClipboardList,
      label: "Stock-take sheets",
      locationSelectorPermission: null,
      requiredPermission: "inventory.write",
      section: "Supply",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/transfers" }],
      description:
        "Monitor transfers, bottlenecks, and exception states across the network.",
      href: toRoute("/admin/transfers"),
      icon: ClipboardList,
      label: "Transfers",
      locationSelectorPermission: null,
      requiredPermission: "stock.supply.manage",
      section: "Supply",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/admin/suppliers" }],
      description: "Manage supplier accounts and purchase relationships.",
      href: toRoute("/admin/suppliers"),
      icon: Store,
      label: "Suppliers",
      requiredPermission: "suppliers.view",
      section: "Supply",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/supplier/catalogue" }],
      description: "Products and variants in your supplier catalogue.",
      href: toRoute("/supplier/catalogue"),
      icon: PackageSearch,
      label: "Catalogue",
      requiredPermission: "supplier.catalog.view",
      section: "My account",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/supplier/orders" }],
      description: "Purchase orders issued to your supplier account.",
      href: toRoute("/supplier/orders"),
      icon: ClipboardList,
      label: "Purchase orders",
      requiredPermission: "supplier.orders.view",
      section: "My account",
    },
    {
      activeMatchers: [{ mode: "descendants", path: "/supplier/inquiries" }],
      description: "Sourcing questions and availability requests.",
      href: toRoute("/supplier/inquiries"),
      icon: MessageSquareText,
      label: "Inquiries",
      requiredPermission: "supplier.inquiries.view",
      section: "My account",
    },
  ];
