import {
  ArrowLeftRight,
  BarChart3,
  Bell,
  Boxes,
  ClipboardList,
  Cog,
  Package,
  Receipt,
  Route as RouteIcon,
  Settings,
  ShoppingCart,
  UserCheck,
  Users,
} from "lucide-react";
import { toRoute } from "@/lib/routes";
import type { NavRegistryEntry, ShellMeta } from "./portal-shell-config.types";

export const SECONDARY_NAV_REGISTRY: readonly NavRegistryEntry[] = [
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/notifications" }],
    description: "Operational updates for the locations you manage.",
    href: toRoute("/manager/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "manager.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/manager/account" }],
    description:
      "Review your account identity, session state, and delivery settings.",
    href: toRoute("/manager/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "manager.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/manager/account/preferences" },
    ],
    description: "Manage your default workspace and delivery settings.",
    href: toRoute("/manager/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "manager.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/stock" }],
    description: "Current stock levels and availability at this location.",
    href: toRoute("/manager/stock"),
    icon: Boxes,
    label: "Location stock",
    requiredPermission: "stock.view",
    section: "Operations",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/manager/stock/reservations" },
    ],
    description: "Active reservations reducing availability at this location.",
    href: toRoute("/manager/stock/reservations"),
    icon: ClipboardList,
    label: "Reservations",
    requiredPermission: "stock.view",
    section: "Operations",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/stock/takes" }],
    description: "Generate printable stock-take sheets for this location.",
    href: toRoute("/manager/stock/takes"),
    icon: ClipboardList,
    label: "Stock-take sheets",
    requiredPermission: "inventory.write",
    section: "Operations",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/transfers" }],
    description: "Inbound and outbound stock transfers for this location.",
    href: toRoute("/manager/transfers"),
    icon: ArrowLeftRight,
    label: "Transfers",
    requiredPermission: "transfers.view",
    section: "Operations",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/staff" }],
    description: "Workers and managers assigned to this location.",
    href: toRoute("/manager/staff"),
    icon: Users,
    label: "Staff performance",
    requiredPermission: "staff.view",
    section: "Operations",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/manager/settings/documents" },
    ],
    description: "Configure official printed details for managed locations.",
    href: toRoute("/manager/settings/documents"),
    icon: Settings,
    label: "Location documents",
    requiredPermission: "settings.location_documents.manage",
    section: "Operations",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/notifications" }],
    description: "Operational updates affecting your day-to-day work.",
    href: toRoute("/worker/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "worker.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/worker/account" }],
    description:
      "Review your account identity, session state, and delivery settings.",
    href: toRoute("/worker/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "worker.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/worker/account/preferences" },
    ],
    description: "Manage your default workspace and live alert settings.",
    href: toRoute("/worker/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "worker.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/stock" }],
    description: "Stock items visible to you at your assigned location.",
    href: toRoute("/worker/stock"),
    icon: Boxes,
    label: "My stock",
    requiredPermission: "worker.stock.view",
    section: "My work",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/transfers" }],
    description: "Transfer requests involving your assigned stock.",
    href: toRoute("/worker/transfers"),
    icon: ArrowLeftRight,
    label: "My transfers",
    requiredPermission: "worker.transfers.view",
    section: "My work",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/assignments" }],
    description: "Stock items currently assigned to you.",
    href: toRoute("/worker/assignments"),
    icon: Package,
    label: "Assignments",
    requiredPermission: "worker.assignments.view",
    section: "My work",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/handovers" }],
    description: "Handover records and ownership transfers.",
    href: toRoute("/worker/handovers"),
    icon: UserCheck,
    label: "Handovers",
    requiredPermission: "worker.handovers.view",
    section: "My work",
  },
  {
    activeMatchers: [
      { mode: "exact", path: "/worker/sales" },
      { mode: "descendants", path: "/worker/sales" },
    ],
    description: "Process a new sale at your location.",
    href: toRoute("/worker/sales"),
    icon: ShoppingCart,
    label: "New sale",
    requiredPermission: "pos.sales.process",
    section: "Sales",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/worker/sales/history" }],
    description: "Your sales history and generated invoices.",
    href: toRoute("/worker/sales/history"),
    icon: Receipt,
    label: "Sales history",
    requiredPermission: "pos.sales.view",
    section: "Sales",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/assignments" }],
    description: "Assign product variants to workers at this location.",
    href: toRoute("/manager/assignments"),
    icon: UserCheck,
    label: "Assignments",
    requiredPermission: "stock.assignments.manage",
    section: "Operations",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/manager/sales" }],
    description: "All POS sales and invoices for this location.",
    href: toRoute("/manager/sales"),
    icon: BarChart3,
    label: "Sales",
    requiredPermission: "pos.sales.manage",
    section: "Operations",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/manager/stock/supply-requests" },
    ],
    description: "Review and respond to worker stock restocking requests.",
    href: toRoute("/manager/stock/supply-requests"),
    icon: ClipboardList,
    label: "Supply requests",
    requiredPermission: "stock.supply.manage",
    section: "Operations",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/worker/stock/supply-requests" },
    ],
    description: "View and manage your stock restocking requests.",
    href: toRoute("/worker/stock/supply-requests"),
    icon: ClipboardList,
    label: "Supply requests",
    requiredPermission: "stock.supply.request",
    section: "My work",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/agent/routes" }],
    description: "Your route map and stop sequence.",
    href: toRoute("/agent/routes"),
    icon: RouteIcon,
    label: "Routes",
    requiredPermission: "agent.routes.view",
    section: "Delivery",
  },
];

export const SHELL_META: ShellMeta = {
  emptyNotificationCopy:
    "Events, alerts, and updates relevant to your role will appear here.",
  heading: "Shop operations",
};
