import {
  Bell,
  ClipboardList,
  MapPin,
  ShieldCheck,
  UserCheck,
  Users,
} from "lucide-react";
import { toRoute } from "@/lib/routes";
import type { NavRegistryEntry } from "./portal-shell-config.types";
import { PRIMARY_SETTINGS_NAV_REGISTRY } from "./portal-shell-registry.primary.settings";

export const ADMIN_ACCESS_NAV_REGISTRY: readonly NavRegistryEntry[] = [
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/notifications" }],
    description: "Operational events and alerts across the platform.",
    href: toRoute("/admin/notifications"),
    icon: Bell,
    label: "Notifications",
    locationSelectorPermission: null,
    requiredPermission: "admin.dashboard.view",
    section: "Overview",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/users" }],
    description: "Manage users, assignments, and access state.",
    href: toRoute("/admin/users"),
    icon: Users,
    label: "Users",
    locationSelectorPermission: null,
    requiredPermission: "users.view",
    section: "Administration",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/staff" }],
    description: "Review managers and workers across locations.",
    href: toRoute("/admin/staff"),
    icon: UserCheck,
    label: "Staff",
    locationSelectorPermission: null,
    requiredPermission: "users.view",
    section: "Administration",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/locations" }],
    description: "Create and maintain stores and warehouses.",
    href: toRoute("/admin/locations"),
    icon: MapPin,
    label: "Locations",
    locationSelectorPermission: null,
    requiredPermission: "locations.view",
    section: "Administration",
  },
  ...PRIMARY_SETTINGS_NAV_REGISTRY,
  {
    activeMatchers: [{ mode: "exact", path: "/admin/locations/new" }],
    description: "Create a new store or warehouse.",
    href: toRoute("/admin/locations/new"),
    icon: MapPin,
    label: "New location",
    locationSelectorPermission: null,
    requiredPermission: "locations.create",
    section: "Administration",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/access" }],
    description: "Access health, role coverage, and recent access changes.",
    href: toRoute("/admin/access"),
    icon: ShieldCheck,
    label: "Access overview",
    locationSelectorPermission: null,
    requiredPermission: "access.roles.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/roles" }],
    description: "Create and manage role definitions for the platform.",
    href: toRoute("/admin/access/roles"),
    icon: ShieldCheck,
    label: "Roles",
    locationSelectorPermission: null,
    requiredPermission: "access.roles.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/users" }],
    description: "Review user role coverage and assigned location scopes.",
    href: toRoute("/admin/access/users"),
    icon: Users,
    label: "User access",
    locationSelectorPermission: null,
    requiredPermission: "access.users.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/access/roles/new" }],
    description: "Create a new custom role.",
    href: toRoute("/admin/access/roles/new"),
    icon: ShieldCheck,
    label: "New role",
    locationSelectorPermission: null,
    requiredPermission: "access.roles.manage",
    section: "Access",
    sidebar: false,
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/admin/access/permissions" },
    ],
    description: "Inspect the permission catalogue and current role coverage.",
    href: toRoute("/admin/access/permissions"),
    icon: UserCheck,
    label: "Permissions",
    locationSelectorPermission: null,
    requiredPermission: "access.permissions.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/audit" }],
    description: "Review recent access-control changes and overrides.",
    href: toRoute("/admin/access/audit"),
    icon: ClipboardList,
    label: "Audit log",
    locationSelectorPermission: null,
    requiredPermission: "access.audit.view",
    section: "Access",
  },
];
