import {
  Bell,
  Boxes,
  ClipboardList,
  MapPin,
  PackageSearch,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Store,
  Truck,
  UserCheck,
  Users,
} from "lucide-react";
import { toRoute } from "@/lib/routes";
import type { NavRegistryEntry } from "./portal-shell-config.types";

export const PRIMARY_SECTION_NAV_REGISTRY: readonly NavRegistryEntry[] = [
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/notifications" }],
    description: "Operational events and alerts across the platform.",
    href: toRoute("/admin/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "admin.dashboard.view",
    section: "Overview",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/users" }],
    description: "Manage users, assignments, and access state.",
    href: toRoute("/admin/users"),
    icon: Users,
    label: "Users",
    requiredPermission: "users.view",
    section: "Administration",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/locations" }],
    description: "Create and maintain stores and warehouses.",
    href: toRoute("/admin/locations"),
    icon: MapPin,
    label: "Locations",
    requiredPermission: "locations.view",
    section: "Administration",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/settings/documents" }],
    description: "Configure official documents, brand identity, and money defaults.",
    href: toRoute("/admin/settings/documents"),
    icon: Settings,
    label: "Settings",
    requiredPermission: "settings.documents.view",
    section: "Administration",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/locations/new" }],
    description: "Create a new store or warehouse.",
    href: toRoute("/admin/locations/new"),
    icon: MapPin,
    label: "New location",
    requiredPermission: "locations.create",
    section: "Administration",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/access" }],
    description: "Access health, role coverage, and recent access changes.",
    href: toRoute("/admin/access"),
    icon: ShieldCheck,
    label: "Access overview",
    requiredPermission: "access.roles.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/roles" }],
    description: "Create and manage role definitions for the platform.",
    href: toRoute("/admin/access/roles"),
    icon: ShieldCheck,
    label: "Roles",
    requiredPermission: "access.roles.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/users" }],
    description: "Review user role coverage and assigned location scopes.",
    href: toRoute("/admin/access/users"),
    icon: Users,
    label: "User access",
    requiredPermission: "access.users.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/access/roles/new" }],
    description: "Create a new custom role.",
    href: toRoute("/admin/access/roles/new"),
    icon: ShieldCheck,
    label: "New role",
    requiredPermission: "access.roles.manage",
    section: "Access",
    sidebar: false,
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/admin/access/permissions" },
    ],
    description: "Inspect the permission catalogue and current role coverage.",
    href: toRoute("/admin/access/permissions"),
    icon: UserCheck,
    label: "Permissions",
    requiredPermission: "access.permissions.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/access/audit" }],
    description: "Review recent access-control changes and overrides.",
    href: toRoute("/admin/access/audit"),
    icon: ClipboardList,
    label: "Audit log",
    requiredPermission: "access.audit.view",
    section: "Access",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/orders" }],
    description: "View and manage customer orders across all locations.",
    href: toRoute("/admin/orders"),
    icon: ShoppingCart,
    label: "Orders",
    requiredPermission: "orders.view",
    section: "Commerce",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/deliveries" }],
    description: "Track and manage delivery operations platform-wide.",
    href: toRoute("/admin/deliveries"),
    icon: Truck,
    label: "Deliveries",
    requiredPermission: "deliveries.view",
    section: "Commerce",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/products" }],
    description: "Manage products, variants, and catalogue structure.",
    href: toRoute("/admin/products"),
    icon: PackageSearch,
    label: "Products",
    requiredPermission: "catalog.view",
    section: "Catalog",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/products/new" }],
    description: "Create a new product.",
    href: toRoute("/admin/products/new"),
    icon: PackageSearch,
    label: "New product",
    requiredPermission: "catalog.products.manage",
    section: "Catalog",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/products/brands" }],
    description: "Create and manage brand entities for the catalogue.",
    href: toRoute("/admin/products/brands"),
    icon: Store,
    label: "Brands",
    requiredPermission: "catalog.brands.manage",
    section: "Catalog",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/products/brands/new" }],
    description: "Create a new brand.",
    href: toRoute("/admin/products/brands/new"),
    icon: Store,
    label: "New brand",
    requiredPermission: "catalog.brands.manage",
    section: "Catalog",
    sidebar: false,
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/admin/products/categories" },
    ],
    description: "Create and manage product categories.",
    href: toRoute("/admin/products/categories"),
    icon: Boxes,
    label: "Categories",
    requiredPermission: "catalog.categories.manage",
    section: "Catalog",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/products/categories/new" }],
    description: "Create a new category.",
    href: toRoute("/admin/products/categories/new"),
    icon: Boxes,
    label: "New category",
    requiredPermission: "catalog.categories.manage",
    section: "Catalog",
    sidebar: false,
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/stock/balances" }],
    description: "On-hand, reserved, and available stock per location.",
    href: toRoute("/admin/stock/balances"),
    icon: Boxes,
    label: "Stock levels",
    requiredPermission: "inventory.read",
    section: "Supply",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/admin/stock/reservations" },
    ],
    description: "Inspect active stock reservations across the platform.",
    href: toRoute("/admin/stock/reservations"),
    icon: Boxes,
    label: "Reservations",
    requiredPermission: "inventory.read",
    section: "Supply",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/admin/suppliers" }],
    description: "Manage supplier accounts and purchase relationships.",
    href: toRoute("/admin/suppliers"),
    icon: Store,
    label: "Suppliers",
    requiredPermission: "suppliers.view",
    section: "Supply",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/supplier/catalogue" }],
    description: "Products and variants in your supplier catalogue.",
    href: toRoute("/supplier/catalogue"),
    icon: PackageSearch,
    label: "Catalogue",
    requiredPermission: "supplier.catalog.view",
    section: "My account",
  },
];
