import {
  Bell,
  Building2,
  ClipboardList,
  Cog,
  ReceiptText,
  ShieldCheck,
  ShoppingCart,
  Truck,
} from "lucide-react";
import { toRoute } from "@/lib/routes";
import type { NavRegistryEntry } from "./portal-shell-config.types";

export const PRIMARY_OVERVIEW_NAV_REGISTRY: readonly NavRegistryEntry[] = [
  {
    activeMatchers: [{ mode: "exact", path: "/admin" }],
    description: "System overview and launch points for admin work.",
    href: toRoute("/admin"),
    icon: ShieldCheck,
    label: "Admin overview",
    requiredPermission: "admin.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/manager" }],
    description: "Live summary for the assigned location.",
    href: toRoute("/manager"),
    icon: Building2,
    label: "Location overview",
    requiredPermission: "manager.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/worker" }],
    description: "Assigned stock, tasks, and handover activity.",
    href: toRoute("/worker"),
    icon: ClipboardList,
    label: "My overview",
    requiredPermission: "worker.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/supplier" }],
    description: "Purchase orders and fulfilment status.",
    href: toRoute("/supplier"),
    icon: ShoppingCart,
    label: "Supplier dashboard",
    requiredPermission: "supplier.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/admin/account" }],
    description:
      "Review your account identity, session state, and delivery settings.",
    href: toRoute("/admin/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "admin.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/admin/account/preferences" },
    ],
    description:
      "Manage your default workspace and notification delivery settings.",
    href: toRoute("/admin/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "admin.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/supplier/notifications" }],
    description: "Operational updates relevant to your supplier account.",
    href: toRoute("/supplier/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "supplier.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/supplier/account" }],
    description:
      "Review your supplier account identity, session state, and delivery settings.",
    href: toRoute("/supplier/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "supplier.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/supplier/account/preferences" },
    ],
    description:
      "Manage your supplier default workspace and delivery settings.",
    href: toRoute("/supplier/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "supplier.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/agent" }],
    description: "Deliveries assigned to you for today.",
    href: toRoute("/agent"),
    icon: Truck,
    label: "Delivery dashboard",
    requiredPermission: "agent.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/customer" }],
    description:
      "Invoices, orders, and account updates for your customer profile.",
    href: toRoute("/customer"),
    icon: ReceiptText,
    label: "Customer dashboard",
    requiredPermission: "customer.dashboard.view",
    section: "Overview",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/customer/notifications" }],
    description: "Account updates relevant to your customer profile.",
    href: toRoute("/customer/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "customer.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/customer/account" }],
    description: "Review your customer account identity and session state.",
    href: toRoute("/customer/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "customer.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/customer/account/preferences" },
    ],
    description: "Manage your default workspace and alert delivery settings.",
    href: toRoute("/customer/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "customer.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "descendants", path: "/agent/notifications" }],
    description:
      "Operational updates relevant to your route and delivery work.",
    href: toRoute("/agent/notifications"),
    icon: Bell,
    label: "Notifications",
    requiredPermission: "agent.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [{ mode: "exact", path: "/agent/account" }],
    description:
      "Review your delivery account identity, session state, and alert settings.",
    href: toRoute("/agent/account"),
    icon: Cog,
    label: "Profile",
    requiredPermission: "agent.dashboard.view",
    section: "Account",
  },
  {
    activeMatchers: [
      { mode: "descendants", path: "/agent/account/preferences" },
    ],
    description: "Manage your default workspace and alert delivery settings.",
    href: toRoute("/agent/account/preferences"),
    icon: Cog,
    label: "Preferences",
    requiredPermission: "agent.dashboard.view",
    section: "Account",
  },
];
