import type { StockTakeLine, StockTakeSessionDetail } from "@shop/contracts";
import ExcelJS from "exceljs";

const baseHeaders = [
  "line",
  "counted",
  "notes",
  "product",
  "variant",
  "sku",
  "unit",
] as const;

const assistedHeaders = [
  ...baseHeaders,
  "systemOnHand",
  "reserved",
  "available",
  "variance",
] as const;

type WorkbookHeader = (typeof assistedHeaders)[number];

const headerLabels: Record<WorkbookHeader, string> = {
  available: "Available",
  counted: "Counted quantity",
  line: "Line #",
  notes: "Notes",
  product: "Product",
  reserved: "Reserved",
  sku: "SKU",
  systemOnHand: "System on hand",
  unit: "Unit",
  variance: "Variance",
  variant: "Variant",
};

type StockTakeXlsxFile = {
  body: Buffer;
  contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
  filename: string;
};

export async function toStockTakeXlsxFile(
  session: StockTakeSessionDetail,
): Promise<StockTakeXlsxFile> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Shop App";
  workbook.created = new Date(session.generatedAt);
  workbook.modified = new Date(session.generatedAt);
  workbook.subject = "Stock-take workbook";
  workbook.title = `Stock-take workbook ${session.stockTakeReference}`;

  const worksheet = workbook.addWorksheet("Stock Take", {
    pageSetup: {
      fitToPage: true,
      fitToWidth: 1,
      orientation: "landscape",
      paperSize: 9,
    },
    views: [{ state: "frozen", topLeftCell: "A10", ySplit: 9 }],
  });
  const headers = selectHeaders(session);

  applyMetadata(worksheet, session);
  applyHeaderRow(worksheet, headers);
  applyDataRows(worksheet, session.lines, headers);
  applyColumnWidths(worksheet, headers);
  await worksheet.protect("", {
    formatColumns: false,
    formatRows: false,
    insertRows: false,
    selectLockedCells: false,
    selectUnlockedCells: true,
  });

  const buffer = await workbook.xlsx.writeBuffer();

  return {
    body: Buffer.from(buffer),
    contentType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    filename: `${safeFilename(session.stockTakeReference)}-sheet.xlsx`,
  };
}

function selectHeaders(
  session: StockTakeSessionDetail,
): readonly WorkbookHeader[] {
  if (session.mode === "assisted" && !session.blankSheet) {
    return assistedHeaders;
  }

  return baseHeaders;
}

function applyMetadata(
  worksheet: ExcelJS.Worksheet,
  session: StockTakeSessionDetail,
) {
  worksheet.mergeCells("A1:D1");
  worksheet.getCell("A1").value = "Stock-take workbook";
  worksheet.getCell("A1").font = { bold: true, size: 16 };
  worksheet.getCell("A1").alignment = { vertical: "middle" };

  const metadata = [
    ["Reference", session.stockTakeReference],
    ["Location", `${session.locationName} (${session.locationSlug})`],
    ["Mode", session.mode === "blind" ? "Blind count" : "Assisted count"],
    ["Generated", formatDateTime(session.generatedAt)],
    ["Generated by", session.generatedByUserSlug ?? "Unknown"],
    [
      "Instructions",
      session.blankSheet
        ? "Fill the highlighted Counted quantity and Notes columns. No active SKUs were found, so catalog creation remains a separate review step."
        : "Fill the highlighted Counted quantity and Notes columns only. The other columns are locked and will be validated after upload.",
    ],
  ] as const;

  metadata.forEach(([label, value], index) => {
    const row = worksheet.getRow(index + 2);
    row.getCell(1).value = label;
    row.getCell(1).font = { bold: true };
    row.getCell(2).value = value;
  });
  worksheet.mergeCells("B7:H7");
  worksheet.getRow(7).height = 32;
  worksheet.getCell("B7").alignment = { wrapText: true, vertical: "top" };
}

function applyHeaderRow(
  worksheet: ExcelJS.Worksheet,
  headers: readonly WorkbookHeader[],
) {
  const row = worksheet.getRow(9);
  headers.forEach((header, index) => {
    const cell = row.getCell(index + 1);
    cell.value = headerLabels[header];
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      fgColor: { argb: header === "counted" ? "FFB45309" : "FF1C5C57" },
      pattern: "solid",
      type: "pattern",
    };
    if (header === "notes") {
      cell.fill = {
        fgColor: { argb: "FF2F6F64" },
        pattern: "solid",
        type: "pattern",
      };
    }
  });
}

function applyDataRows(
  worksheet: ExcelJS.Worksheet,
  lines: StockTakeLine[],
  headers: readonly WorkbookHeader[],
) {
  lines.forEach((line, lineIndex) => {
    const row = worksheet.getRow(lineIndex + 10);
    const rowValues = rowForLine(line);
    headers.forEach((header, headerIndex) => {
      const cell = row.getCell(headerIndex + 1);
      cell.value = rowValues[header];
      cell.alignment = { vertical: "top", wrapText: true };
      if (header === "counted" || header === "notes") {
        cell.fill = {
          fgColor: { argb: "FFFFF4CC" },
          pattern: "solid",
          type: "pattern",
        };
      }
      cell.protection = {
        locked: header !== "counted" && header !== "notes",
      };
    });
  });
}

function applyColumnWidths(
  worksheet: ExcelJS.Worksheet,
  headers: readonly WorkbookHeader[],
) {
  const widths: Record<WorkbookHeader, number> = {
    available: 14,
    counted: 18,
    line: 10,
    notes: 28,
    product: 28,
    reserved: 14,
    sku: 18,
    systemOnHand: 16,
    unit: 14,
    variance: 14,
    variant: 22,
  };

  headers.forEach((header, index) => {
    worksheet.getColumn(index + 1).width = widths[header];
  });
  worksheet.getColumn("A").alignment = { horizontal: "center" };
}

function rowForLine(
  line: StockTakeLine,
): Record<WorkbookHeader, string | number> {
  return {
    available: line.availableQuantity ?? "",
    counted: line.countedQuantity ?? "",
    line: line.lineNumber,
    notes: safeText(line.note ?? ""),
    product: safeText(line.productName),
    reserved: line.reservedQuantity ?? "",
    sku: safeText(line.sku),
    systemOnHand: line.systemOnHand ?? "",
    unit: safeText(line.unitOfMeasure),
    variance: line.variance ?? "",
    variant: safeText(line.variantName),
  };
}

function safeText(value: string): string {
  return /^[\t\r\n ]*[=+\-@]/.test(value) ? `'${value}` : value;
}

function safeFilename(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]+/g, "-") || "stock-take";
}

function formatDateTime(value: string): string {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }).format(new Date(value));
}
