import type { StockTakeLine, StockTakeSessionDetail } from "@shop/contracts";
import ExcelJS from "exceljs";

const baseHeaders = [
  "lineNumber",
  "productName",
  "variantName",
  "sku",
  "unitOfMeasure",
  "countedQuantity",
  "notes",
] as const;

const assistedHeaders = [
  ...baseHeaders,
  "systemOnHand",
  "reservedQuantity",
  "availableQuantity",
  "variance",
] as const;

type WorkbookHeader = (typeof assistedHeaders)[number];

type StockTakeXlsxFile = {
  body: Buffer;
  contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
  filename: string;
};

export async function toStockTakeXlsxFile(
  session: StockTakeSessionDetail,
): Promise<StockTakeXlsxFile> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Shop App";
  workbook.created = new Date(session.generatedAt);
  workbook.modified = new Date(session.generatedAt);
  workbook.subject = "Stock-take workbook";
  workbook.title = `Stock-take workbook ${session.stockTakeReference}`;

  const worksheet = workbook.addWorksheet("Stock Take", {
    pageSetup: {
      fitToPage: true,
      fitToWidth: 1,
      orientation: "landscape",
      paperSize: 9,
    },
    views: [{ state: "frozen", ySplit: 8 }],
  });
  const headers = selectHeaders(session);

  applyMetadata(worksheet, session);
  applyHeaderRow(worksheet, headers);
  applyDataRows(worksheet, session.lines, headers);
  applyColumnWidths(worksheet, headers);
  await worksheet.protect("", {
    formatColumns: false,
    formatRows: false,
    insertRows: false,
    selectLockedCells: true,
    selectUnlockedCells: true,
  });

  const buffer = await workbook.xlsx.writeBuffer();

  return {
    body: Buffer.from(buffer),
    contentType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    filename: `${safeFilename(session.stockTakeReference)}-sheet.xlsx`,
  };
}

function selectHeaders(
  session: StockTakeSessionDetail,
): readonly WorkbookHeader[] {
  if (session.mode === "assisted" && !session.blankSheet) {
    return assistedHeaders;
  }

  return baseHeaders;
}

function applyMetadata(
  worksheet: ExcelJS.Worksheet,
  session: StockTakeSessionDetail,
) {
  worksheet.mergeCells("A1:D1");
  worksheet.getCell("A1").value = "Stock-take workbook";
  worksheet.getCell("A1").font = { bold: true, size: 16 };
  worksheet.getCell("A1").alignment = { vertical: "middle" };

  const metadata = [
    ["Reference", session.stockTakeReference],
    ["Location", `${session.locationName} (${session.locationSlug})`],
    ["Mode", session.mode === "blind" ? "Blind count" : "Assisted count"],
    ["Generated", session.generatedAt],
    ["Generated by", session.generatedByUserSlug ?? "Unknown"],
    [
      "Instructions",
      session.blankSheet
        ? "No active SKUs were found. Fill manual rows for physical counting; catalog creation remains a separate review step."
        : "Edit only countedQuantity and notes. System-owned columns are locked and will be validated after upload.",
    ],
  ] as const;

  metadata.forEach(([label, value], index) => {
    const row = worksheet.getRow(index + 2);
    row.getCell(1).value = label;
    row.getCell(1).font = { bold: true };
    row.getCell(2).value = value;
  });
  worksheet.mergeCells("B7:H7");
  worksheet.getRow(7).height = 32;
  worksheet.getCell("B7").alignment = { wrapText: true, vertical: "top" };
}

function applyHeaderRow(
  worksheet: ExcelJS.Worksheet,
  headers: readonly WorkbookHeader[],
) {
  const row = worksheet.getRow(9);
  headers.forEach((header, index) => {
    const cell = row.getCell(index + 1);
    cell.value = header;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      fgColor: { argb: "FF1C5C57" },
      pattern: "solid",
      type: "pattern",
    };
  });
}

function applyDataRows(
  worksheet: ExcelJS.Worksheet,
  lines: StockTakeLine[],
  headers: readonly WorkbookHeader[],
) {
  lines.forEach((line, lineIndex) => {
    const row = worksheet.getRow(lineIndex + 10);
    const rowValues = rowForLine(line);
    headers.forEach((header, headerIndex) => {
      const cell = row.getCell(headerIndex + 1);
      cell.value = rowValues[header];
      cell.alignment = { vertical: "top", wrapText: true };
      cell.protection = {
        locked: header !== "countedQuantity" && header !== "notes",
      };
    });
  });
}

function applyColumnWidths(
  worksheet: ExcelJS.Worksheet,
  headers: readonly WorkbookHeader[],
) {
  const widths: Record<WorkbookHeader, number> = {
    availableQuantity: 16,
    countedQuantity: 18,
    lineNumber: 12,
    notes: 28,
    productName: 28,
    reservedQuantity: 18,
    sku: 18,
    systemOnHand: 16,
    unitOfMeasure: 16,
    variance: 14,
    variantName: 22,
  };

  headers.forEach((header, index) => {
    worksheet.getColumn(index + 1).width = widths[header];
  });
  worksheet.getColumn("A").alignment = { horizontal: "center" };
}

function rowForLine(
  line: StockTakeLine,
): Record<WorkbookHeader, string | number> {
  return {
    availableQuantity: line.availableQuantity ?? "",
    countedQuantity: line.countedQuantity ?? "",
    lineNumber: line.lineNumber,
    notes: safeText(line.note ?? ""),
    productName: safeText(line.productName),
    reservedQuantity: line.reservedQuantity ?? "",
    sku: safeText(line.sku),
    systemOnHand: line.systemOnHand ?? "",
    unitOfMeasure: safeText(line.unitOfMeasure),
    variance: line.variance ?? "",
    variantName: safeText(line.variantName),
  };
}

function safeText(value: string): string {
  return /^[\t\r\n ]*[=+\-@]/.test(value) ? `'${value}` : value;
}

function safeFilename(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]+/g, "-") || "stock-take";
}
