import type { StockTakeLine, StockTakeSessionDetail } from "@shop/contracts";
import {
  drawStockTakeSignatureArea,
  renderStockTakePdfTable,
  STOCK_TAKE_PDF_PAGE,
} from "./stock-take-pdf-layout.js";

export function renderStockTakeBookletPdf(
  doc: PDFKit.PDFDocument,
  session: StockTakeSessionDetail,
): void {
  const showExpected = session.mode === "assisted" && !session.blankSheet;
  drawHeader(doc, session, "Physical Stock-Take Booklet");
  if (session.blankSheet) drawBlankSheetInstructions(doc);
  renderStockTakePdfTable(doc, {
    columns: showExpected ? bookletAssistedColumns : bookletColumns,
    lines: session.lines,
    row: (line) => bookletRow(line, showExpected),
  });
  drawStockTakeSignatureArea(doc);
}

export function renderStockTakeVarianceReportPdf(
  doc: PDFKit.PDFDocument,
  session: StockTakeSessionDetail,
): void {
  const summary = buildVarianceSummary(session.lines);
  drawHeader(doc, session, "Final Variance Report");
  doc.font("Helvetica-Bold").fontSize(9).fillColor("#15110f");
  doc.text(
    `Applied rows: ${summary.appliedRows}`,
    STOCK_TAKE_PDF_PAGE.left,
    150,
  );
  doc.text(
    `Changed rows: ${summary.changedRows}`,
    STOCK_TAKE_PDF_PAGE.left + 130,
    150,
  );
  doc.text(
    `No-change rows: ${summary.noChangeRows}`,
    STOCK_TAKE_PDF_PAGE.left + 260,
    150,
  );
  doc.text(
    `Positive delta: ${summary.positiveDelta}`,
    STOCK_TAKE_PDF_PAGE.left,
    166,
  );
  doc.text(
    `Negative delta: ${summary.negativeDelta}`,
    STOCK_TAKE_PDF_PAGE.left + 130,
    166,
  );
  renderStockTakePdfTable(doc, {
    columns: reportColumns,
    lines: session.lines,
    row: reportRow,
  });
}

export function writeStockTakePageNumbers(
  doc: PDFKit.PDFDocument,
  reference: string,
): void {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    doc.fillColor("#6f665f").font("Helvetica").fontSize(7);
    doc.text(`${reference} | Page ${index + 1} of ${range.count}`, 42, 790, {
      align: "center",
      width: STOCK_TAKE_PDF_PAGE.right - STOCK_TAKE_PDF_PAGE.left,
    });
  }
}

function drawHeader(
  doc: PDFKit.PDFDocument,
  session: StockTakeSessionDetail,
  title: string,
): void {
  doc.rect(0, 0, doc.page.width, doc.page.height).fill("#f6f7f4");
  doc.roundedRect(24, 24, doc.page.width - 48, 132, 4).fill("#ffffff");
  doc.rect(24, 24, 5, 132).fill("#1c5c57");
  doc.fillColor("#15110f").font("Helvetica-Bold").fontSize(17);
  doc.text(title, STOCK_TAKE_PDF_PAGE.left, STOCK_TAKE_PDF_PAGE.top, {
    width: 290,
  });
  doc
    .fontSize(11)
    .text(session.stockTakeReference, STOCK_TAKE_PDF_PAGE.left, 68);
  doc.fillColor("#6f665f").font("Helvetica").fontSize(8.5);
  doc.text(
    `${session.locationName} - ${session.locationSlug}`,
    STOCK_TAKE_PDF_PAGE.left,
    88,
  );
  doc.text(`Mode: ${formatMode(session.mode)}`, STOCK_TAKE_PDF_PAGE.left, 106);
  doc.text(`Status: ${session.status}`, STOCK_TAKE_PDF_PAGE.left + 146, 106);
  doc.text(
    `Generated: ${formatDateTime(session.generatedAt)}`,
    STOCK_TAKE_PDF_PAGE.left,
    124,
  );
  doc.text(
    `Generated by: ${session.generatedByUserSlug ?? "Unknown"}`,
    360,
    62,
  );
  doc.text(`Lines: ${session.lineCount}`, 360, 82);
  doc.text(`Blank sheet: ${session.blankSheet ? "Yes" : "No"}`, 360, 102);
}

function drawBlankSheetInstructions(doc: PDFKit.PDFDocument): void {
  doc.fillColor("#6f665f").font("Helvetica").fontSize(8.5);
  doc.text(
    "No active SKUs were found for this scope. Use these controlled manual rows for physical counting; catalog creation remains a separate review step.",
    STOCK_TAKE_PDF_PAGE.left,
    154,
    { width: STOCK_TAKE_PDF_PAGE.right - STOCK_TAKE_PDF_PAGE.left },
  );
}

const bookletColumns = [
  ["#", 22],
  ["SKU", 72],
  ["Item", 166],
  ["Unit", 44],
  ["Counted", 56],
  ["Notes", 132],
] as const;

const bookletAssistedColumns = [
  ["#", 22],
  ["SKU", 64],
  ["Item", 142],
  ["Unit", 38],
  ["Expected", 52],
  ["Counted", 52],
  ["Notes", 122],
] as const;

const reportColumns = [
  ["#", 22],
  ["SKU", 66],
  ["Item", 142],
  ["Previous", 56],
  ["Counted", 52],
  ["Delta", 42],
  ["Movement", 58],
  ["Notes", 54],
] as const;

function bookletRow(line: StockTakeLine, showExpected: boolean): string[] {
  const base = [
    String(line.lineNumber),
    line.sku,
    formatItem(line),
    line.unitOfMeasure,
  ];
  return showExpected
    ? [...base, formatNullableNumber(line.systemOnHand), "", line.note ?? ""]
    : [...base, "", line.note ?? ""];
}

function reportRow(line: StockTakeLine): string[] {
  const counted = line.countedQuantity;
  const delta = line.appliedDelta;
  const previous =
    counted !== null && delta !== null ? String(counted - delta) : "";
  return [
    String(line.lineNumber),
    line.sku,
    formatItem(line),
    previous,
    formatNullableNumber(counted),
    formatNullableNumber(delta),
    delta === null || delta === 0 ? "No" : "Yes",
    line.note ?? "",
  ];
}

function buildVarianceSummary(lines: StockTakeLine[]) {
  const applied = lines.filter((line) => line.countedQuantity !== null);
  return {
    appliedRows: applied.length,
    changedRows: applied.filter((line) => (line.appliedDelta ?? 0) !== 0)
      .length,
    negativeDelta: applied.reduce(
      (sum, line) => sum + Math.min(line.appliedDelta ?? 0, 0),
      0,
    ),
    noChangeRows: applied.filter((line) => (line.appliedDelta ?? 0) === 0)
      .length,
    positiveDelta: applied.reduce(
      (sum, line) => sum + Math.max(line.appliedDelta ?? 0, 0),
      0,
    ),
  };
}

function formatItem(line: StockTakeLine): string {
  return [line.productName, line.variantName].filter(Boolean).join(" / ");
}

function formatMode(mode: StockTakeSessionDetail["mode"]): string {
  return mode === "blind" ? "Blind count" : "Assisted count";
}

function formatDateTime(value: string): string {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }).format(new Date(value));
}

function formatNullableNumber(value: number | null): string {
  return value === null ? "" : String(value);
}
