import type { SeedProduct } from "./catalog-seed-types.js";

export const catalogSeedProductsA = [
  {
    slug: "evercarry-market-tote",
    name: "EverCarry Market Tote",
    description: "A structured everyday tote with a zip-top closure, bottle sleeve, and reinforced base panel.",
    categorySlug: "tote-bags",
    brandSlug: "evercarry",
    countryOfOrigin: "GH",
    isTaxable: true,
    taxCategory: "bags",
    priceIncludesTax: false,
    features: [
      "Zip-top main compartment",
      "Internal water bottle sleeve",
      "Padded shoulder straps",
    ],
    options: [
      { name: "Color", values: ["Sand", "Olive"] },
      { name: "Size", values: ["Medium", "Large"] },
    ],
    variants: [
      {
        slug: "evercarry-market-tote-sand-medium",
        name: "Sand / Medium",
        sku: "BAG-ECT-001",
        barcode: "1200000000013",
        unitOfMeasure: "piece",
        costPrice: "32.00",
        sellingPrice: "55.00",
        attributes: { Color: "Sand", Size: "Medium" },
        weightGrams: 780,
        dimensionsCm: { length: 34, width: 12, height: 29 },
        packagingType: "dust bag",
        manufacturerPartNumber: "ECT-SND-M",
        customsCode: "420222",
        isDefault: true,
      },
      {
        slug: "evercarry-market-tote-sand-large",
        name: "Sand / Large",
        sku: "BAG-ECT-002",
        barcode: "1200000000020",
        unitOfMeasure: "piece",
        costPrice: "35.00",
        sellingPrice: "59.00",
        attributes: { Color: "Sand", Size: "Large" },
        weightGrams: 860,
        dimensionsCm: { length: 38, width: 13, height: 32 },
        packagingType: "dust bag",
        manufacturerPartNumber: "ECT-SND-L",
        customsCode: "420222",
        isDefault: false,
      },
      {
        slug: "evercarry-market-tote-olive-medium",
        name: "Olive / Medium",
        sku: "BAG-ECT-003",
        barcode: "1200000000037",
        unitOfMeasure: "piece",
        costPrice: "32.00",
        sellingPrice: "55.00",
        attributes: { Color: "Olive", Size: "Medium" },
        weightGrams: 780,
        dimensionsCm: { length: 34, width: 12, height: 29 },
        packagingType: "dust bag",
        manufacturerPartNumber: "ECT-OLV-M",
        customsCode: "420222",
        isDefault: false,
      },
    ],
  },
  {
    slug: "nomad-lane-transit-laptop-bag",
    name: "Nomad Lane Transit Laptop Bag",
    description: "A padded commuter bag with a suspended laptop sleeve, cable pockets, and trolley pass-through.",
    categorySlug: "laptop-bags",
    brandSlug: "nomad-lane",
    countryOfOrigin: "VN",
    isTaxable: true,
    taxCategory: "bags",
    priceIncludesTax: false,
    features: [
      "Suspended 16-inch laptop sleeve",
      "Rear trolley sleeve",
      "Weather-resistant shell",
    ],
    options: [
      { name: "Color", values: ["Black", "Slate"] },
      { name: "Capacity", values: ["20L", "28L"] },
    ],
    variants: [
      {
        slug: "nomad-lane-transit-laptop-bag-black-20l",
        name: "Black / 20L",
        sku: "BAG-NLT-001",
        barcode: "1200000000044",
        unitOfMeasure: "piece",
        costPrice: "48.00",
        sellingPrice: "84.00",
        attributes: { Color: "Black", Capacity: "20L" },
        weightGrams: 1120,
        dimensionsCm: { length: 41, width: 14, height: 30 },
        packagingType: "carton",
        manufacturerPartNumber: "NLT-BLK-20",
        customsCode: "420212",
        isDefault: true,
      },
      {
        slug: "nomad-lane-transit-laptop-bag-black-28l",
        name: "Black / 28L",
        sku: "BAG-NLT-002",
        barcode: "1200000000051",
        unitOfMeasure: "piece",
        costPrice: "52.00",
        sellingPrice: "92.00",
        attributes: { Color: "Black", Capacity: "28L" },
        weightGrams: 1280,
        dimensionsCm: { length: 44, width: 16, height: 32 },
        packagingType: "carton",
        manufacturerPartNumber: "NLT-BLK-28",
        customsCode: "420212",
        isDefault: false,
      },
      {
        slug: "nomad-lane-transit-laptop-bag-slate-20l",
        name: "Slate / 20L",
        sku: "BAG-NLT-003",
        barcode: "1200000000068",
        unitOfMeasure: "piece",
        costPrice: "48.00",
        sellingPrice: "84.00",
        attributes: { Color: "Slate", Capacity: "20L" },
        weightGrams: 1120,
        dimensionsCm: { length: 41, width: 14, height: 30 },
        packagingType: "carton",
        manufacturerPartNumber: "NLT-SLT-20",
        customsCode: "420212",
        isDefault: false,
      },
    ],
  },
] satisfies SeedProduct[];

