import type { SeedProduct } from "./catalog-seed-types.js";

export const catalogSeedProductsB = [
  {
    slug: "cedar-thread-city-crossbody",
    name: "Cedar Thread City Crossbody",
    description: "A compact daily crossbody with organized card slots, a magnetic flap, and an adjustable strap.",
    categorySlug: "crossbody-bags",
    brandSlug: "cedar-thread",
    countryOfOrigin: "CN",
    isTaxable: true,
    taxCategory: "bags",
    priceIncludesTax: false,
    features: [
      "Magnetic flap closure",
      "Built-in card divider",
      "Adjustable webbing strap",
    ],
    options: [
      { name: "Color", values: ["Stone", "Ink"] },
      { name: "Strap", values: ["Standard", "Extended"] },
    ],
    variants: [
      {
        slug: "cedar-thread-city-crossbody-stone-standard",
        name: "Stone / Standard",
        sku: "BAG-CTC-001",
        barcode: "1200000000075",
        unitOfMeasure: "piece",
        costPrice: "18.00",
        sellingPrice: "34.00",
        attributes: { Color: "Stone", Strap: "Standard" },
        weightGrams: 420,
        dimensionsCm: { length: 24, width: 8, height: 17 },
        packagingType: "poly bag",
        manufacturerPartNumber: "CTC-STN-STD",
        customsCode: "420222",
        isDefault: true,
      },
      {
        slug: "cedar-thread-city-crossbody-ink-standard",
        name: "Ink / Standard",
        sku: "BAG-CTC-002",
        barcode: "1200000000082",
        unitOfMeasure: "piece",
        costPrice: "18.00",
        sellingPrice: "34.00",
        attributes: { Color: "Ink", Strap: "Standard" },
        weightGrams: 420,
        dimensionsCm: { length: 24, width: 8, height: 17 },
        packagingType: "poly bag",
        manufacturerPartNumber: "CTC-INK-STD",
        customsCode: "420222",
        isDefault: false,
      },
      {
        slug: "cedar-thread-city-crossbody-ink-extended",
        name: "Ink / Extended",
        sku: "BAG-CTC-003",
        barcode: "1200000000099",
        unitOfMeasure: "piece",
        costPrice: "19.50",
        sellingPrice: "36.00",
        attributes: { Color: "Ink", Strap: "Extended" },
        weightGrams: 450,
        dimensionsCm: { length: 24, width: 8, height: 17 },
        packagingType: "poly bag",
        manufacturerPartNumber: "CTC-INK-EXT",
        customsCode: "420222",
        isDefault: false,
      },
    ],
  },
  {
    slug: "harbor-house-weekender-duffel",
    name: "Harbor House Weekender Duffel",
    description: "A canvas travel duffel with a shoe tunnel, luggage tag pocket, and detachable shoulder strap.",
    categorySlug: "travel-bags",
    brandSlug: "harbor-house",
    countryOfOrigin: "IN",
    isTaxable: true,
    taxCategory: "bags",
    priceIncludesTax: false,
    features: [
      "Dedicated shoe tunnel",
      "Detachable shoulder strap",
      "Brass hardware trim",
    ],
    options: [
      { name: "Color", values: ["Navy", "Cocoa"] },
      { name: "Size", values: ["40L", "55L"] },
    ],
    variants: [
      {
        slug: "harbor-house-weekender-duffel-navy-40l",
        name: "Navy / 40L",
        sku: "BAG-HHW-001",
        barcode: "1200000000105",
        unitOfMeasure: "piece",
        costPrice: "44.00",
        sellingPrice: "78.00",
        attributes: { Color: "Navy", Size: "40L" },
        weightGrams: 1360,
        dimensionsCm: { length: 48, width: 24, height: 28 },
        packagingType: "carton",
        manufacturerPartNumber: "HHW-NVY-40",
        customsCode: "420292",
        isDefault: true,
      },
      {
        slug: "harbor-house-weekender-duffel-navy-55l",
        name: "Navy / 55L",
        sku: "BAG-HHW-002",
        barcode: "1200000000112",
        unitOfMeasure: "piece",
        costPrice: "49.00",
        sellingPrice: "88.00",
        attributes: { Color: "Navy", Size: "55L" },
        weightGrams: 1540,
        dimensionsCm: { length: 54, width: 26, height: 31 },
        packagingType: "carton",
        manufacturerPartNumber: "HHW-NVY-55",
        customsCode: "420292",
        isDefault: false,
      },
      {
        slug: "harbor-house-weekender-duffel-cocoa-40l",
        name: "Cocoa / 40L",
        sku: "BAG-HHW-003",
        barcode: "1200000000129",
        unitOfMeasure: "piece",
        costPrice: "44.00",
        sellingPrice: "78.00",
        attributes: { Color: "Cocoa", Size: "40L" },
        weightGrams: 1360,
        dimensionsCm: { length: 48, width: 24, height: 28 },
        packagingType: "carton",
        manufacturerPartNumber: "HHW-COC-40",
        customsCode: "420292",
        isDefault: false,
      },
    ],
  },
] satisfies SeedProduct[];

