import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type {
  StockTakeDetailResponse,
  StockTakeLine,
} from "@/lib/react-query/stock-takes";

type StockTakeBookletPrintProps = {
  stockTake: StockTakeDetailResponse;
};

export function StockTakeBookletPrint({
  stockTake,
}: StockTakeBookletPrintProps) {
  const showExpected = stockTake.mode === "assisted" && !stockTake.blankSheet;

  return (
    <article className="stock-take-print-root flex flex-col gap-5">
      <PrintStyles />
      <PrintFixedFooter stockTake={stockTake} />
      <section className="stock-take-print-page rounded-xl border border-border bg-card p-5 shadow-sm">
        <BookletHeader stockTake={stockTake} />
        <CountTable lines={stockTake.lines} showExpected={showExpected} />
        <SignatureArea />
        <BookletFooter stockTake={stockTake} />
      </section>
    </article>
  );
}

function BookletHeader({ stockTake }: { stockTake: StockTakeDetailResponse }) {
  return (
    <header className="grid gap-4 border-b border-border pb-4 md:grid-cols-[minmax(0,1fr)_18rem]">
      <div>
        <p className="type-kicker text-muted-foreground">Stock-take booklet</p>
        <h1 className="type-page-title text-foreground">
          {stockTake.stockTakeReference}
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          {stockTake.locationName} - {stockTake.locationSlug}
        </p>
      </div>
      <dl className="grid grid-cols-2 gap-3 text-sm">
        <MetaItem label="Mode" value={formatMode(stockTake.mode)} />
        <MetaItem label="Status" value={stockTake.status} />
        <MetaItem label="Lines" value={String(stockTake.lineCount)} />
        <MetaItem
          label="Generated"
          value={formatDateTime(stockTake.generatedAt)}
        />
        <MetaItem
          label="Generated by"
          value={stockTake.generatedByUserSlug ?? "Unknown"}
        />
        <MetaItem
          label="Blank sheet"
          value={stockTake.blankSheet ? "Yes" : "No"}
        />
      </dl>
    </header>
  );
}

function CountTable({
  lines,
  showExpected,
}: {
  lines: StockTakeLine[];
  showExpected: boolean;
}) {
  return (
    <section className="mt-5">
      <h2 className="font-heading text-base font-medium text-foreground">
        Count lines
      </h2>
      <div className="mt-3 overflow-hidden rounded-lg border border-border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-12">#</TableHead>
              <TableHead>SKU</TableHead>
              <TableHead>Item</TableHead>
              <TableHead>Unit</TableHead>
              {showExpected ? <TableHead>Expected</TableHead> : null}
              <TableHead>Counted</TableHead>
              <TableHead>Notes</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {lines.map((line) => (
              <TableRow key={`${line.lineNumber}:${line.sku}`}>
                <TableCell>{line.lineNumber}</TableCell>
                <TableCell className="font-mono">{line.sku}</TableCell>
                <TableCell>
                  <span className="block font-medium">{line.productName}</span>
                  <span className="block text-xs text-muted-foreground">
                    {line.variantName ?? "Default variant"}
                  </span>
                </TableCell>
                <TableCell>{line.unitOfMeasure ?? "each"}</TableCell>
                {showExpected ? (
                  <TableCell>{getExpectedQuantity(line)}</TableCell>
                ) : null}
                <TableCell className="min-w-24" />
                <TableCell className="min-w-36" />
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </section>
  );
}

function SignatureArea() {
  return (
    <section className="mt-8 grid gap-4 sm:grid-cols-3">
      {["Counted by", "Verified by", "Approved by"].map((label) => (
        <div
          className="min-h-28 rounded-lg border border-border p-3"
          key={label}
        >
          <p className="type-data-label text-muted-foreground">{label}</p>
          <div className="mt-10 border-b border-border" />
          <p className="mt-2 text-xs text-muted-foreground">
            Name and signature
          </p>
        </div>
      ))}
    </section>
  );
}

function PrintFixedFooter({
  stockTake,
}: {
  stockTake: StockTakeDetailResponse;
}) {
  return (
    <div className="stock-take-print-fixed-footer hidden">
      <span>{stockTake.stockTakeReference}</span>
      <span>{stockTake.locationName}</span>
      <span className="stock-take-print-page-number">Page </span>
      <span>{formatDateTime(stockTake.generatedAt)}</span>
    </div>
  );
}

function BookletFooter({ stockTake }: { stockTake: StockTakeDetailResponse }) {
  return (
    <footer className="mt-6 flex flex-wrap justify-between gap-3 border-t border-border pt-3 text-xs text-muted-foreground">
      <span>Reference: {stockTake.stockTakeReference}</span>
      <span>CSV: {stockTake.sheetCsvUrl}</span>
    </footer>
  );
}

function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="type-data-label text-muted-foreground">{label}</dt>
      <dd className="mt-1 font-medium text-foreground">{value}</dd>
    </div>
  );
}

function PrintStyles() {
  return (
    <style>{`
      @media print {
        @page { size: A4; margin: 12mm 12mm 18mm; }
        body * { visibility: hidden; }
        .stock-take-print-root,
        .stock-take-print-root * { visibility: visible; }
        .stock-take-print-root {
          position: absolute;
          inset: 0;
          width: 100%;
          background: white;
          color: black;
        }
        .stock-take-no-print { display: none !important; }
        .stock-take-print-page {
          border: 0;
          box-shadow: none;
          padding: 0;
        }
        [data-slot="table-container"] { overflow: visible; }
        [data-slot="table"] { font-size: 9pt; }
        [data-slot="table-header"] { display: table-header-group; }
        [data-slot="table-row"] { break-inside: avoid; }
        .stock-take-print-fixed-footer {
          align-items: center;
          border-top: 1px solid currentColor;
          bottom: 0;
          color: black;
          display: flex;
          font-size: 8pt;
          gap: 8mm;
          justify-content: space-between;
          left: 0;
          padding-top: 2mm;
          position: fixed;
          right: 0;
        }
        .stock-take-print-page-number::after { content: counter(page); }
      }
    `}</style>
  );
}

function formatMode(mode: StockTakeDetailResponse["mode"]) {
  return mode === "blind" ? "Blind count" : "Assisted count";
}

function formatDateTime(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function getExpectedQuantity(line: StockTakeLine) {
  return line.expectedQuantity ?? line.systemOnHand ?? "";
}
