import type {
  ManagedLocationRecord,
  ManagedUserRecord,
} from "@/lib/admin-models";

// Temporary prototype records for backlog-only UI exploration.
// Remove this module when admin pages switch to real API contracts.

export const PROTOTYPE_ADMIN_LOCATIONS: ManagedLocationRecord[] = [
  {
    createdAt: "2025-01-15T09:00:00Z",
    id: "loc-001",
    managerName: "Jane Smith",
    managerUserId: "user-002",
    name: "Downtown Store",
    pendingTransfers: 2,
    referenceNumber: "LOC-0001",
    slug: "downtown-store",
    staffCount: 14,
    status: "active",
    type: "store",
    zoneNames: ["Front of house", "Back room", "Returns"],
  },
  {
    createdAt: "2025-01-18T10:30:00Z",
    id: "loc-002",
    managerName: null,
    managerUserId: null,
    name: "West District Warehouse",
    pendingTransfers: 5,
    referenceNumber: "LOC-0002",
    slug: "west-district-warehouse",
    staffCount: 9,
    status: "active",
    type: "warehouse",
    zoneNames: ["Inbound", "Cold storage", "Bulk racking"],
  },
  {
    createdAt: "2025-02-01T11:00:00Z",
    id: "loc-003",
    managerName: "Sarah Mensah",
    managerUserId: "user-008",
    name: "East Branch",
    pendingTransfers: 1,
    referenceNumber: "LOC-0003",
    slug: "east-branch",
    staffCount: 11,
    status: "active",
    type: "store",
    zoneNames: ["Shop floor", "Seasonal", "Collection point"],
  },
  {
    createdAt: "2025-02-15T09:00:00Z",
    id: "loc-004",
    managerName: null,
    managerUserId: null,
    name: "Central Distribution Hub",
    pendingTransfers: 7,
    referenceNumber: "LOC-0004",
    slug: "central-distribution-hub",
    staffCount: 18,
    status: "active",
    type: "warehouse",
    zoneNames: ["Inbound", "Outbound", "Damaged stock", "Pick faces"],
  },
  {
    createdAt: "2025-03-01T10:00:00Z",
    id: "loc-005",
    managerName: null,
    managerUserId: null,
    name: "North Outlet",
    pendingTransfers: 0,
    referenceNumber: "LOC-0005",
    slug: "north-outlet",
    staffCount: 0,
    status: "inactive",
    type: "store",
    zoneNames: ["Sales floor", "Returns"],
  },
  {
    createdAt: "2025-03-19T13:00:00Z",
    id: "loc-006",
    managerName: null,
    managerUserId: null,
    name: "Airport Express Store",
    pendingTransfers: 1,
    referenceNumber: "LOC-0006",
    slug: "airport-express-store",
    staffCount: 6,
    status: "active",
    type: "store",
    zoneNames: ["Grab and go", "Storage cage"],
  },
];

export const PROTOTYPE_ADMIN_USERS: ManagedUserRecord[] = [
  {
    assignedLocationIds: [],
    createdAt: "2025-01-15T09:00:00Z",
    email: "admin@shop.local",
    firstName: "Solomon",
    id: "user-001",
    lastName: "Aboagye",
    notes: "Primary super admin account.",
    preferredPortal: "admin",
    requiresPasswordChange: false,
    roles: ["basic_user", "admin"],
    status: "active",
  },
  {
    assignedLocationIds: ["loc-001"],
    createdAt: "2025-02-01T10:30:00Z",
    email: "jane.smith@shop.local",
    firstName: "Jane",
    id: "user-002",
    lastName: "Smith",
    notes: "Owns downtown staffing and escalations.",
    preferredPortal: "manager",
    requiresPasswordChange: false,
    roles: ["basic_user", "manager"],
    status: "active",
  },
  {
    assignedLocationIds: ["loc-001"],
    createdAt: "2025-02-14T14:00:00Z",
    email: "robert.wilson@shop.local",
    firstName: "Robert",
    id: "user-003",
    lastName: "Wilson",
    notes: "Needs onboarding reset after first assignment.",
    preferredPortal: "worker",
    requiresPasswordChange: true,
    roles: ["basic_user", "worker"],
    status: "active",
  },
  {
    assignedLocationIds: [],
    createdAt: "2025-03-01T08:00:00Z",
    email: "maria.garcia@shop.local",
    firstName: "Maria",
    id: "user-004",
    lastName: "Garcia",
    notes: "Supplier catalogue contact.",
    preferredPortal: "supplier",
    requiresPasswordChange: false,
    roles: ["basic_user", "supplier"],
    status: "active",
  },
  {
    assignedLocationIds: [],
    createdAt: "2025-03-15T11:00:00Z",
    email: "tom.chen@shop.local",
    firstName: "Tom",
    id: "user-005",
    lastName: "Chen",
    notes: "Delivery fleet pilot account.",
    preferredPortal: "agent",
    requiresPasswordChange: true,
    roles: ["basic_user", "agent"],
    status: "active",
  },
  {
    assignedLocationIds: ["loc-006"],
    createdAt: "2025-01-20T16:00:00Z",
    email: "alice.johnson@shop.local",
    firstName: "Alice",
    id: "user-006",
    lastName: "Johnson",
    notes: "Suspended pending access review.",
    preferredPortal: "manager",
    requiresPasswordChange: false,
    roles: ["basic_user", "manager"],
    status: "suspended",
  },
  {
    assignedLocationIds: ["loc-002"],
    createdAt: "2025-04-01T09:00:00Z",
    email: "david.osei@shop.local",
    firstName: "David",
    id: "user-007",
    lastName: "Osei",
    notes: "Warehouse worker on west district cycle count.",
    preferredPortal: "worker",
    requiresPasswordChange: false,
    roles: ["basic_user", "worker"],
    status: "active",
  },
  {
    assignedLocationIds: ["loc-003"],
    createdAt: "2025-04-05T10:00:00Z",
    email: "sarah.mensah@shop.local",
    firstName: "Sarah",
    id: "user-008",
    lastName: "Mensah",
    notes: "Cross-trained store lead.",
    preferredPortal: "manager",
    requiresPasswordChange: false,
    roles: ["basic_user", "manager", "worker"],
    status: "active",
  },
  {
    assignedLocationIds: [],
    createdAt: "2025-04-07T12:45:00Z",
    email: "customer.one@shop.local",
    firstName: "Ama",
    id: "user-009",
    lastName: "Owusu",
    notes: "Commerce-only account with no staff portal.",
    preferredPortal: null,
    requiresPasswordChange: false,
    roles: ["basic_user"],
    status: "active",
  },
];
